# Generated by Django 4.0.4 on 2022-05-20 22:00
import os

from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):

    def create_superuser_forward(apps, schema_editor):
        user = get_user_model()
        u, _ = user.objects.get_or_create(**{
            'username': 'root',
            'first_name': 'System',
            'last_name': 'Administrator',
            'is_superuser': True,
            'is_staff': True,
        })
        root_password = os.environ.get('ROOT_PASSWORD', '123')
        u.set_password(root_password)
        u.save()

    def create_superuser_reverse(apps, schema_editor):
        pass

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser_forward, create_superuser_reverse),
    ]
