# Generated by Django 4.0.4 on 2022-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterStart', models.PositiveIntegerField(default=0, verbose_name='Meter start')),
                ('timestampStart', models.DateTimeField(verbose_name='Time stamp start')),
                ('meterStop', models.PositiveIntegerField(default=0, verbose_name='Meter stop')),
                ('timestampStop', models.DateTimeField(verbose_name='Time stamp stop')),
                ('energy', models.FloatField(default=0, help_text='Energy fee in € per kWh', verbose_name='Energy fee')),
                ('time', models.FloatField(default=0, help_text='Time fee in € per hour', verbose_name='Time fee')),
                ('transaction', models.FloatField(default=0, help_text='Transaction fee in € per service', verbose_name='Transaction fee')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-timestampStart', '-timestampStop'],
            },
        ),
    ]
